collections:
  '1x':
    output: true
    permalink: /:path:output_ext
  '15':
    output: true
    permalink: /:path:output_ext
version: '1.5'
package_version: '1.5.0'
sg_download_link: 'http://packages.couchbase.com/releases/couchbase-sync-gateway/1.4.1/'
sg_package_name: 'couchbase-sync-gateway-community_1.4.1-3_x86_64'
swagger_url: 'http://couchbase-docs.s3.amazonaws.com/mobile/1.4/rest-apis/couchbase-lite.json'