collections:
  '20':
    output: true
    permalink: /:path:output_ext
version: '2.0'
references:
  objc: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-objc/db004/'
  swift: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-swift/db004/docsets/CouchbaseLiteSwift.docset/Contents/Resources/Documents/'
  csharp: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-net/db004/'
  java: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-java/db004/'