collections:
  '1x':
    output: true
    permalink: /:path:output_ext
  '14':
    output: true
    permalink: /:path:output_ext
version: '1.4'
package_version: '1.4.0'
sg_download_link: 'http://packages.couchbase.com/releases/couchbase-sync-gateway/1.4.0/'
sg_package_name: 'couchbase-sync-gateway-community_1.4.0-2_x86_64'