title: Couchbase Mobile
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Couchbase Mobile documentation: API references and Guides.
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

assets:
  dirname: img

defaults:
- scope:
    path: ''
    type: post
  value:
    layout: post
- scope:
    path: docs
    type: page
  values:
    layout: docs
- scope:
    path: ready
    type: page
  values:
    layout: ready
- scope:
    path: 'ready/swagger'
    type: page
  values:
    layout: swagger

# Build settings
#markdown: kramdown
# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

exclude:
  - "*.screenflow"

version: "1.3"

keep_files:
  - "references"
